[package]
name = "roottask"
description = "The vaxpunk root task, freestanding C"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
kernel = { path = "../kernel" }
tcpip = { path = "../tcpip" }

[build-dependencies]
vasm = { path = "../vtools/crates/vasm" }
vlink = { path = "../vtools/crates/vlink" }
vmacro = { path = "../vtools/crates/vmacro" }
vms-obj = { path = "../vtools/crates/vms-obj" }
ods-image = { path = "../ods/crates/ods-image" }
