[package]
name = "vrun"
description = "Runs vaxpunk images at EL0 in a bare-metal QEMU virt machine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vms-obj = { path = "../vms-obj" }

[dev-dependencies]
vasm = { path = "../vasm" }
vlib = { path = "../vlib" }
vlink = { path = "../vlink" }
