//! On-disk structures.
//!
//! Every fixed-layout structure is a byte buffer with accessors generated by
//! [`layout!`] from one table of offsets, so reading and writing a field is
//! the same line of code: the two cannot drift, and bytes nobody names
//! (reserved areas, fields added by later VMS versions) survive untouched.
//! See `docs/` for what each field means.

mod dir;
mod header;
mod home;
mod scb;

pub use dir::{DirBlock, DirRecord, MAX_RECORD, NameType};
pub use header::{Fi2, Fi5, Header, Ident, Pointer, RecordAttrs, decode_map, encode_map};
pub use home::HomeBlock;
pub use scb::Scb;

use core::fmt;

/// Size of a logical block, in bytes. Files-11 knows no other.
pub const BLOCK: usize = 512;
pub type Block = [u8; BLOCK];

/// A value stored little-endian at the start of a byte slice.
pub trait Field: Sized {
    fn get(b: &[u8]) -> Self;
    fn put(&self, b: &mut [u8]);
}

macro_rules! int_field {
    ($($t:ty),*) => {$(
        impl Field for $t {
            fn get(b: &[u8]) -> Self {
                let mut a = [0; size_of::<$t>()];
                a.copy_from_slice(&b[..size_of::<$t>()]);
                <$t>::from_le_bytes(a)
            }
            fn put(&self, b: &mut [u8]) {
                b[..size_of::<$t>()].copy_from_slice(&self.to_le_bytes())
            }
        }
    )*};
}
int_field!(u8, u16, u32, u64);

impl<const N: usize> Field for [u8; N] {
    fn get(b: &[u8]) -> Self {
        let mut a = [0; N];
        a.copy_from_slice(&b[..N]);
        a
    }
    fn put(&self, b: &mut [u8]) {
        b[..N].copy_from_slice(self)
    }
}

/// Declares a structure as a wrapper around bytes, with a getter and a setter
/// per field. The buffer type is generic: an owned block, or a borrowed area
/// of one (the ident area moves around inside a file header).
macro_rules! layout {
    ($(#[$m:meta])* pub struct $name:ident {
        $($(#[$fm:meta])* $get:ident, $set:ident: $t:ty = $off:expr;)*
    }) => {
        $(#[$m])*
        #[derive(Clone, Copy, PartialEq, Eq)]
        pub struct $name<B = $crate::layout::Block>(pub B);

        impl<B: AsRef<[u8]>> $name<B> {
            $($(#[$fm])* pub fn $get(&self) -> $t {
                $crate::layout::Field::get(&self.0.as_ref()[$off..])
            })*
        }

        impl<B: AsMut<[u8]>> $name<B> {
            $(pub fn $set(&mut self, v: $t) {
                $crate::layout::Field::put(&v, &mut self.0.as_mut()[$off..])
            })*
        }
    };
}
pub(crate) use layout;

/// Additive 16-bit checksum of the first `words` words: the home block, file
/// header and SCB all use it.
pub fn checksum(b: &[u8], words: usize) -> u16 {
    b[..words * 2].as_chunks::<2>().0.iter().fold(0u16, |s, w| s.wrapping_add(u16::from_le_bytes([w[0], w[1]])))
}

/// File identifier: a 24-bit file number, a sequence number that changes each
/// time the number is reused, and the relative volume number (0 off volume
/// sets). On disk: number low word, sequence, RVN byte, number high byte.
#[derive(Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Fid {
    pub num: u32,
    pub seq: u16,
    pub rvn: u8,
}

impl Fid {
    pub const fn new(num: u32, seq: u16) -> Fid {
        Fid { num, seq, rvn: 0 }
    }
    pub fn is_zero(&self) -> bool {
        self.num == 0
    }
}

impl Field for Fid {
    fn get(b: &[u8]) -> Fid {
        Fid { num: u16::get(b) as u32 | (b[5] as u32) << 16, seq: u16::get(&b[2..]), rvn: b[4] }
    }
    fn put(&self, b: &mut [u8]) {
        (self.num as u16).put(b);
        self.seq.put(&mut b[2..]);
        b[4] = self.rvn;
        b[5] = (self.num >> 16) as u8;
    }
}

impl fmt::Display for Fid {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "({},{},{})", self.num, self.seq, self.rvn)
    }
}

impl fmt::Debug for Fid {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        fmt::Display::fmt(self, f)
    }
}
