! Run by check.py. DKA0 and DKA100 hold volumes ods made (ODS-2 and
! ODS-5); VMS checks them, then copies their [T] trees to a volume of its
! own on DKA200, which ods compares with the originals.
SET PROCESS/PARSE_STYLE=EXTENDED
MOUNT/OVERRIDE=IDENTIFICATION/NOWRITE DKA0:
MOUNT/OVERRIDE=IDENTIFICATION/NOWRITE DKA100:
ANALYZE/DISK_STRUCTURE DKA0:
ANALYZE/DISK_STRUCTURE DKA100:
DIRECTORY/SIZE=ALL/FILE_ID DKA0:[000000...]
DIRECTORY/SIZE=ALL/FILE_ID DKA100:[000000...]
INITIALIZE/STRUCTURE_LEVEL=5 DKA200: COPIES
MOUNT DKA200: COPIES
BACKUP DKA0:[T...]*.*;* DKA200:[ODS2...]*.*;*/OWNER_UIC=ORIGINAL
BACKUP DKA100:[T...]*.*;* DKA200:[ODS5...]*.*;*/OWNER_UIC=ORIGINAL
DIRECTORY/SIZE=ALL DKA200:[000000...]
ANALYZE/DISK_STRUCTURE DKA200:
DISMOUNT DKA200:
DISMOUNT DKA0:
DISMOUNT DKA100:
