timeout: 0
serial: yes
verbose: yes

/seL4 milestone 0
    protocol: limine
    path: boot():/boot/shim.elf
    module_path: boot():/boot/kernel.elf
    module_string: kernel
    module_path: boot():/boot/roottask.elf
    module_string: roottask
